--- #YAML:1.0
name:               Variable-Magic
version:            0.27
abstract:           Associate user-defined magic to variables from Perl.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:      0
    Exporter:  0
    XSLoader:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
build_requires:
    Config:                        0
    ExtUtils::MakeMaker:           0
    Test::More:                    0
resources:
    bugtracker:     http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Variable-Magic
    repository:     http://git.profvince.com/perl/modules/Variable-Magic.git
