--- #YAML:1.0
name:                Variable-Magic
version:             0.05
abstract:            Associate user-defined magic to variables from Perl.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Carp:                          0
    Exporter:                      0
    Test::More:                    0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Vincent Pit <perl@profvince.com>
